name: Update version CI

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: version number

jobs:

  update_version:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Update version
      run: |
        ./update_version.sh "${{ github.event.inputs.version }}"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Updated ${{github.repository}} version to '${{ github.event.inputs.version }}'"
        title: "Update ${{github.repository}} for '${{github.event.head_commit.message}}'"
        body: |
          This pull request updates ${{github.repository}} version to '${{ github.event.inputs.version }}'.
        branch: production-promotion
        base: main