name: Update version CI

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: version number

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Update version
      run: |
        cd $GITHUB_WORKSPACE
        ./update_version.sh "${{github.sha}}"

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated version to ${{github.repository}}@${{github.sha}}
        commit_author: ${{github.actor}} <noreply@github.com>

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Updated ${{github.repository}} version to ${{github.repository}}@${{github.sha}}"
        title: "Update ${{github.repository}} for '${{github.event.head_commit.message}}'"
        body: |
          This pull request updates ${{github.repository}} version to ${{github.repository}}@${{github.sha}}.
          Original commit message: "${{github.event.head_commit.message}}"
          Actor: @${{github.actor}}
        author: ${{github.actor}} <noreply@github.com>
        delete-branch: true
        branch: upgrade/${{github.repository}}